# Generated by Django 3.2.6 on 2021-09-02 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayStoreGames',
            new_name='PlayStoreGame',
        ),
    ]
