# Generated by Django 3.2.6 on 2021-09-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_playstoregames_playstoregame'),
    ]

    operations = [
        migrations.AddField(
            model_name='playstoregame',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2009-03-03 12:22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playstoregame',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
