# Generated by Django 3.2.6 on 2021-09-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210902_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playstoregame',
            name='details_link',
            field=models.URLField(max_length=1000, verbose_name='Details Link'),
        ),
        migrations.AlterField(
            model_name='playstoregamescategory',
            name='category_link',
            field=models.URLField(max_length=1000, verbose_name='Category Link'),
        ),
    ]
