# Generated by Django 3.2.6 on 2021-09-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210902_0438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayStoreGame',
            new_name='Games',
        ),
    ]
