# Generated by Django 3.2.6 on 2021-09-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_playstoregame_games'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='games',
            old_name='name',
            new_name='title',
        ),
    ]
