# Generated by Django 3.2.6 on 2021-09-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210902_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='games',
            name='download_link',
            field=models.URLField(max_length=1000, null=True, verbose_name='Download Link'),
        ),
        migrations.AddField(
            model_name='games',
            name='image_link',
            field=models.URLField(max_length=1000, null=True, verbose_name='Image Link'),
        ),
        migrations.AddField(
            model_name='games',
            name='rating',
            field=models.CharField(max_length=500, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='games',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
