# Generated by Django 3.2.6 on 2021-09-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210902_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='download_link',
        ),
        migrations.RemoveField(
            model_name='games',
            name='rating',
        ),
        migrations.AddField(
            model_name='games',
            name='app_id',
            field=models.CharField(max_length=500, null=True, verbose_name='App ID'),
        ),
        migrations.AddField(
            model_name='games',
            name='ratings',
            field=models.CharField(max_length=500, null=True, verbose_name='Ratings'),
        ),
        migrations.AddField(
            model_name='games',
            name='score',
            field=models.CharField(max_length=225, null=True, verbose_name='Score'),
        ),
    ]
